import { prisma } from '@/lib/prisma';
import { sendPaymentReminder } from '@/lib/automations/notifications';
import { sendTemplate as sendWhatsAppTemplate } from '@/lib/whatsapp/client';
import { deriveInvoiceStatus } from '@/lib/accounts-receivable';
import type { AutomationRule } from '@prisma/client';

const UNANSWERED_EMAIL_HOURS = 24;
const PENDING_ORDER_DAYS = 3;

async function ensureTask(params: {
  title: string;
  description?: string;
  relatedType: 'INVOICE' | 'SALES_ORDER' | 'PRODUCT' | 'CONTACT' | 'COMPANY';
  relatedId: string;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  dueDate?: Date;
}) {
  const existing = await prisma.task.findFirst({
    where: {
      relatedType: params.relatedType,
      relatedId: params.relatedId,
      title: params.title,
      status: { in: ['TODO', 'IN_PROGRESS'] },
    },
  });
  if (existing) return { created: false };

  await prisma.task.create({
    data: {
      title: params.title,
      description: params.description,
      relatedType: params.relatedType,
      relatedId: params.relatedId,
      priority: params.priority || 'MEDIUM',
      dueDate: params.dueDate,
      autoGenerated: true,
    },
  });
  return { created: true };
}

async function logResult(ruleId: string | null, entityType: string, entityId: string, success: boolean, message: string) {
  await prisma.automationLog.create({
    data: { ruleId, entityType, entityId, success, message },
  });
}

async function checkOverdueInvoices() {
  const candidates = await prisma.invoice.findMany({
    where: {
      status: { in: ['SENT', 'PARTIAL'] },
      dueDate: { lt: new Date() },
    },
  });

  let flagged = 0;
  for (const invoice of candidates) {
    // Re-derive rather than blindly forcing OVERDUE: guards against a stale
    // query result (e.g. a payment landed between the query and this loop)
    // ever moving an already-PAID invoice backwards to OVERDUE.
    const status = deriveInvoiceStatus({
      status: invoice.status,
      total: Number(invoice.total),
      amountPaid: Number(invoice.amountPaid),
      dueDate: invoice.dueDate,
    });
    if (status !== 'OVERDUE') continue;

    await prisma.invoice.update({ where: { id: invoice.id }, data: { status } });
    flagged += 1;
    const { created } = await ensureTask({
      title: `Follow up on overdue invoice ${invoice.number}`,
      description: `Invoice ${invoice.number} was due ${invoice.dueDate?.toDateString()} and is unpaid.`,
      relatedType: 'INVOICE',
      relatedId: invoice.id,
      priority: 'HIGH',
    });
    if (created) {
      const result = await sendPaymentReminder(invoice.id).catch((e) => ({ sent: false, reason: String(e) }));
      await logResult(null, 'INVOICE', invoice.id, result.sent, result.sent ? 'Reminder sent' : result.reason || 'not sent');
    }
  }
  return flagged;
}

async function checkPendingOrders() {
  const cutoff = new Date(Date.now() - PENDING_ORDER_DAYS * 24 * 60 * 60 * 1000);
  const pending = await prisma.salesOrder.findMany({
    where: { status: 'DRAFT', createdAt: { lt: cutoff } },
  });

  for (const order of pending) {
    await ensureTask({
      title: `Follow up on pending order ${order.number}`,
      description: `Order ${order.number} has been in draft for more than ${PENDING_ORDER_DAYS} days.`,
      relatedType: 'SALES_ORDER',
      relatedId: order.id,
      priority: 'MEDIUM',
    });
  }
  return pending.length;
}

async function checkLowStock() {
  const levels = await prisma.stockLevel.findMany({
    include: { productVariant: { include: { product: true } }, warehouse: true },
  });

  let flagged = 0;
  for (const level of levels) {
    const reorderPoint = level.productVariant.product.reorderPoint;
    if (!level.productVariant.product.trackInventory) continue;
    if (level.quantity > reorderPoint) continue;

    flagged += 1;
    const { created } = await ensureTask({
      title: `Low stock: ${level.productVariant.product.name} (${level.productVariant.name})`,
      description: `${level.quantity} units left at ${level.warehouse.name}, reorder point is ${reorderPoint}.`,
      relatedType: 'PRODUCT',
      relatedId: level.productVariant.productId,
      priority: 'HIGH',
    });

    if (created) {
      await runRulesForTrigger('LOW_STOCK', {
        productId: level.productVariant.productId,
        productName: level.productVariant.product.name,
        quantity: level.quantity,
      });
    }
  }
  return flagged;
}

async function checkUnansweredEmails() {
  const cutoff = new Date(Date.now() - UNANSWERED_EMAIL_HOURS * 60 * 60 * 1000);
  const unanswered = await prisma.emailMessage.findMany({
    where: {
      direction: 'INBOUND',
      isAnswered: false,
      receivedAt: { lt: cutoff },
      OR: [{ companyId: { not: null } }, { contactId: { not: null } }],
    },
  });

  for (const message of unanswered) {
    await ensureTask({
      title: `Reply to email: ${message.subject || '(no subject)'}`,
      description: `From ${message.fromAddress}, received ${message.receivedAt.toDateString()} and still unanswered.`,
      relatedType: 'CONTACT',
      relatedId: message.contactId || message.companyId || message.id,
      priority: 'MEDIUM',
    });
  }
  return unanswered.length;
}

/** Executes the "actions" of any active configurable rules matching a
 * trigger, in addition to the built-in behavior above. Supported action
 * kinds: create_task, send_whatsapp_template. Extend as needed. */
async function runRulesForTrigger(trigger: AutomationRule['trigger'], context: Record<string, unknown>) {
  const rules = await prisma.automationRule.findMany({ where: { trigger, active: true } });
  for (const rule of rules) {
    try {
      const actions = Array.isArray(rule.actions) ? (rule.actions as unknown[]) : [];
      for (const action of actions as Array<{ kind: string; [key: string]: unknown }>) {
        if (action.kind === 'create_task') {
          await ensureTask({
            title: String(action.title || rule.name),
            description: JSON.stringify(context),
            relatedType: 'PRODUCT',
            relatedId: String(context.productId || rule.id),
            priority: (action.priority as never) || 'MEDIUM',
          });
        } else if (action.kind === 'send_whatsapp_template' && action.to) {
          await sendWhatsAppTemplate({
            to: String(action.to),
            templateName: String(action.templateName || 'hello_world'),
          });
        }
      }
      await logResult(rule.id, 'AUTOMATION_RULE', rule.id, true, 'Executed');
    } catch (err) {
      await logResult(rule.id, 'AUTOMATION_RULE', rule.id, false, String(err));
    }
  }
}

export async function runScheduledAutomations() {
  const results = {
    overdueInvoices: 0,
    pendingOrders: 0,
    lowStock: 0,
    unansweredEmails: 0,
  };

  try {
    results.overdueInvoices = await checkOverdueInvoices();
  } catch (err) {
    await logResult(null, 'SYSTEM', 'overdue-invoices', false, String(err));
  }

  try {
    results.pendingOrders = await checkPendingOrders();
  } catch (err) {
    await logResult(null, 'SYSTEM', 'pending-orders', false, String(err));
  }

  try {
    results.lowStock = await checkLowStock();
  } catch (err) {
    await logResult(null, 'SYSTEM', 'low-stock', false, String(err));
  }

  try {
    results.unansweredEmails = await checkUnansweredEmails();
  } catch (err) {
    await logResult(null, 'SYSTEM', 'unanswered-emails', false, String(err));
  }

  return results;
}
