import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import type { TestDb } from './test-db';
import { startTestDb } from './test-db';

/**
 * Phase 11 (SYSTEM_AUDIT.md E2): a cooldown on overdue-invoice follow-ups.
 * Before this phase, ensureTask()'s dedupe only checked for a currently
 * *open* task — the moment staff marked the follow-up task DONE, the very
 * next scheduler tick recreated it and resent the payment-reminder email,
 * even if the last one went out minutes earlier. See
 * docs/FINANCIAL_ACCURACY_AND_AUTOMATION.md.
 */
describe('Overdue invoice reminder cooldown', () => {
  let db: TestDb;
  let engine: typeof import('../src/lib/automations/engine');

  beforeAll(async () => {
    db = await startTestDb();
    process.env.DATABASE_URL = db.url;
    engine = await import('../src/lib/automations/engine');
  }, 60000);

  afterAll(async () => {
    await db.stop();
  });

  function id() {
    return Math.random().toString(36).slice(2);
  }

  describe('isReminderCooldownActive (pure boundary math)', () => {
    it('never sent (null) is never in cooldown', () => {
      expect(engine.isReminderCooldownActive(null, new Date())).toBe(false);
    });

    it('sent 1ms ago, with a 7-day cooldown: still active', () => {
      const now = new Date('2026-06-15T12:00:00Z');
      const lastSentAt = new Date(now.getTime() - 1);
      expect(engine.isReminderCooldownActive(lastSentAt, now, 7)).toBe(true);
    });

    it('sent exactly 7 days ago, with a 7-day cooldown: no longer active (boundary is exclusive)', () => {
      const now = new Date('2026-06-15T12:00:00Z');
      const lastSentAt = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
      expect(engine.isReminderCooldownActive(lastSentAt, now, 7)).toBe(false);
    });

    it('sent 1ms short of 7 days ago: still active (one ms on the wrong side of the boundary)', () => {
      const now = new Date('2026-06-15T12:00:00Z');
      const lastSentAt = new Date(now.getTime() - (7 * 24 * 60 * 60 * 1000 - 1));
      expect(engine.isReminderCooldownActive(lastSentAt, now, 7)).toBe(true);
    });

    it('sent 8 days ago, with a 7-day cooldown: not active', () => {
      const now = new Date('2026-06-15T12:00:00Z');
      const lastSentAt = new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000);
      expect(engine.isReminderCooldownActive(lastSentAt, now, 7)).toBe(false);
    });

    it('respects a custom cooldown window (e.g. 1 day) independent of the 7-day default', () => {
      const now = new Date('2026-06-15T12:00:00Z');
      const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
      expect(engine.isReminderCooldownActive(twoDaysAgo, now, 1)).toBe(false);
      expect(engine.isReminderCooldownActive(twoDaysAgo, now, 7)).toBe(true);
    });

    it('a lastSentAt in the future (clock skew) is treated as within cooldown, not a negative/expired duration', () => {
      const now = new Date('2026-06-15T12:00:00Z');
      const future = new Date(now.getTime() + 60_000);
      expect(engine.isReminderCooldownActive(future, now, 7)).toBe(true);
    });
  });

  describe('checkOverdueInvoices — task/reminder gating', () => {
    async function makeOverdueInvoice() {
      const company = await db.prisma.company.create({ data: { name: `Co ${id()}`, type: 'CUSTOMER' } });
      // A real recipient email is required for sendPaymentReminder() to
      // reach its own logging step at all (recipientEmail() returning null
      // short-circuits before ever calling sendAndRecord — see
      // src/lib/automations/notifications.ts) — without one, "was a
      // reminder attempt logged" tests would trivially pass for the wrong
      // reason (nothing was ever attempted).
      const contact = await db.prisma.contact.create({
        data: { firstName: 'Jane', lastName: 'Doe', email: `jane-${id()}@example.com`, companyId: company.id },
      });
      return db.prisma.invoice.create({
        data: {
          number: `INV-${id()}`,
          type: 'INVOICE',
          status: 'SENT',
          companyId: company.id,
          contactId: contact.id,
          subtotal: 100,
          total: 100,
          dueDate: new Date(Date.now() - 5 * 86_400_000), // 5 days overdue
        },
      });
    }

    it('an invoice overdue for the first time (no prior reminder): creates the follow-up task and attempts a reminder', async () => {
      const invoice = await makeOverdueInvoice();
      await engine.checkOverdueInvoices();

      const task = await db.prisma.task.findFirst({ where: { relatedType: 'INVOICE', relatedId: invoice.id } });
      expect(task).not.toBeNull();
      expect(task!.autoGenerated).toBe(true);

      // The reminder attempt is always logged (Phase 10), regardless of
      // whether the send itself succeeded in this environment — proves an
      // attempt was made this tick.
      const log = await db.prisma.communicationLog.findFirst({
        where: { relatedType: 'INVOICE', relatedId: invoice.id, templateKey: 'payment_reminder' },
      });
      expect(log).not.toBeNull();

      const updated = await db.prisma.invoice.findUniqueOrThrow({ where: { id: invoice.id } });
      expect(updated.status).toBe('OVERDUE');
    });

    it('a reminder successfully sent 2 days ago (within the 7-day cooldown): the next tick creates NO new task and sends no reminder', async () => {
      const invoice = await makeOverdueInvoice();
      await db.prisma.communicationLog.create({
        data: {
          type: 'EMAIL',
          direction: 'OUTBOUND',
          relatedType: 'INVOICE',
          relatedId: invoice.id,
          templateKey: 'payment_reminder',
          status: 'SENT',
          occurredAt: new Date(Date.now() - 2 * 86_400_000),
        },
      });

      await engine.checkOverdueInvoices();

      const tasks = await db.prisma.task.findMany({ where: { relatedType: 'INVOICE', relatedId: invoice.id } });
      expect(tasks).toHaveLength(0); // task recreation itself is suppressed, not just the email

      const logs = await db.prisma.communicationLog.findMany({
        where: { relatedType: 'INVOICE', relatedId: invoice.id, templateKey: 'payment_reminder' },
      });
      expect(logs).toHaveLength(1); // still just the one we seeded — no new attempt this tick

      // The invoice itself is still correctly (re)marked OVERDUE — the
      // cooldown only suppresses the follow-up/reminder, not the status.
      const updated = await db.prisma.invoice.findUniqueOrThrow({ where: { id: invoice.id } });
      expect(updated.status).toBe('OVERDUE');
    });

    it('a reminder successfully sent 8 days ago (past the 7-day cooldown): the next tick creates a new task and attempts another reminder', async () => {
      const invoice = await makeOverdueInvoice();
      await db.prisma.communicationLog.create({
        data: {
          type: 'EMAIL',
          direction: 'OUTBOUND',
          relatedType: 'INVOICE',
          relatedId: invoice.id,
          templateKey: 'payment_reminder',
          status: 'SENT',
          occurredAt: new Date(Date.now() - 8 * 86_400_000),
        },
      });

      await engine.checkOverdueInvoices();

      const tasks = await db.prisma.task.findMany({ where: { relatedType: 'INVOICE', relatedId: invoice.id } });
      expect(tasks).toHaveLength(1);

      const logs = await db.prisma.communicationLog.findMany({
        where: { relatedType: 'INVOICE', relatedId: invoice.id, templateKey: 'payment_reminder' },
      });
      expect(logs).toHaveLength(2); // the seeded one from 8 days ago + a fresh attempt this tick
    });

    it('a FAILED reminder attempt (e.g. SMTP down) does NOT start a cooldown — the very next tick retries, since the invoice is still just as unreminded', async () => {
      const invoice = await makeOverdueInvoice();
      await db.prisma.communicationLog.create({
        data: {
          type: 'EMAIL',
          direction: 'OUTBOUND',
          relatedType: 'INVOICE',
          relatedId: invoice.id,
          templateKey: 'payment_reminder',
          status: 'FAILED',
          occurredAt: new Date(Date.now() - 60_000), // 1 minute ago
        },
      });

      // No task exists yet (the FAILED attempt was seeded directly, not
      // via a real tick) — a real tick right now should still try again,
      // since only a *successful* send starts the cooldown.
      await engine.checkOverdueInvoices();

      const tasks = await db.prisma.task.findMany({ where: { relatedType: 'INVOICE', relatedId: invoice.id } });
      expect(tasks).toHaveLength(1);
    });

    it('completing the follow-up task early does not itself matter — cooldown is keyed on the last SENT reminder, not on task status', async () => {
      const invoice = await makeOverdueInvoice();
      await engine.checkOverdueInvoices(); // first tick: creates the task, attempts a reminder (likely FAILED in this test env)

      const task = await db.prisma.task.findFirstOrThrow({ where: { relatedType: 'INVOICE', relatedId: invoice.id } });
      await db.prisma.task.update({ where: { id: task.id }, data: { status: 'DONE' } });

      // Simulate that the (failed, in this env) attempt had actually
      // succeeded, by seeding a SENT log dated "just now" — proving the
      // very next tick honors that cooldown regardless of the task having
      // just been completed (the original E2 bug: task completion alone
      // used to be enough to let the next tick re-fire).
      await db.prisma.communicationLog.create({
        data: {
          type: 'EMAIL',
          direction: 'OUTBOUND',
          relatedType: 'INVOICE',
          relatedId: invoice.id,
          templateKey: 'payment_reminder',
          status: 'SENT',
          occurredAt: new Date(),
        },
      });

      await engine.checkOverdueInvoices(); // second tick, immediately after

      const openTasks = await db.prisma.task.findMany({
        where: { relatedType: 'INVOICE', relatedId: invoice.id, status: { in: ['TODO', 'IN_PROGRESS'] } },
      });
      expect(openTasks).toHaveLength(0); // no new open task was recreated
    });
  });
});
