import { prisma } from '@/lib/prisma';
import { requireModule } from '@/lib/session';
import PageHeader from '@/components/PageHeader';
import TaskList from './TaskList';

export default async function TasksPage() {
  await requireModule('tasks');
  const [tasks, users] = await Promise.all([
    prisma.task.findMany({ where: { status: { not: 'CANCELLED' } }, include: { assignee: true }, orderBy: [{ dueDate: 'asc' }] }),
    prisma.user.findMany({ where: { active: true }, orderBy: { name: 'asc' } }),
  ]);

  return (
    <div>
      <PageHeader title="Tasks" subtitle={`${tasks.length} active tasks`} />
      <TaskList
        initial={tasks.map((t) => ({
          id: t.id,
          title: t.title,
          description: t.description,
          status: t.status,
          priority: t.priority,
          dueDate: t.dueDate ? t.dueDate.toISOString() : null,
          assignee: t.assignee ? { id: t.assignee.id, name: t.assignee.name } : null,
          autoGenerated: t.autoGenerated,
        }))}
        users={users.map((u) => ({ id: u.id, name: u.name }))}
      />
    </div>
  );
}
