'use client';

import { useEffect, useState } from 'react';
import Badge from '@/components/Badge';
import { formatDate } from '@/lib/format';

interface User { id: string; name: string }
interface Task {
  id: string;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  dueDate: string | null;
  assignee: User | null;
  autoGenerated: boolean;
}

export default function TaskList({ initial, users }: { initial: Task[]; users: User[] }) {
  const [tasks, setTasks] = useState(initial);
  const [title, setTitle] = useState('');
  const [assigneeId, setAssigneeId] = useState('');
  const [dueDate, setDueDate] = useState('');
  const [priority, setPriority] = useState('MEDIUM');
  const [creating, setCreating] = useState(false);

  useEffect(() => setTasks(initial), [initial]);

  async function createTask(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setCreating(true);
    const res = await fetch('/api/tasks', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title, assigneeId: assigneeId || null, dueDate: dueDate || null, priority }),
    });
    const data = await res.json();
    setTasks((t) => [{ ...data.task, assignee: users.find((u) => u.id === assigneeId) || null }, ...t]);
    setTitle('');
    setDueDate('');
    setCreating(false);
  }

  async function updateStatus(id: string, status: string) {
    setTasks((t) => t.map((task) => (task.id === id ? { ...task, status } : task)));
    await fetch(`/api/tasks/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status }),
    });
  }

  const grouped = {
    TODO: tasks.filter((t) => t.status === 'TODO'),
    IN_PROGRESS: tasks.filter((t) => t.status === 'IN_PROGRESS'),
    DONE: tasks.filter((t) => t.status === 'DONE'),
  };

  return (
    <div>
      <form onSubmit={createTask} className="card p-4 mb-6 flex flex-wrap gap-2 items-end">
        <div className="flex-1 min-w-[200px]">
          <label className="label">New task</label>
          <input className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Task title..." />
        </div>
        <div>
          <label className="label">Assignee</label>
          <select className="input" value={assigneeId} onChange={(e) => setAssigneeId(e.target.value)}>
            <option value="">Unassigned</option>
            {users.map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}
          </select>
        </div>
        <div>
          <label className="label">Due date</label>
          <input type="date" className="input" value={dueDate} onChange={(e) => setDueDate(e.target.value)} />
        </div>
        <div>
          <label className="label">Priority</label>
          <select className="input" value={priority} onChange={(e) => setPriority(e.target.value)}>
            <option value="LOW">Low</option>
            <option value="MEDIUM">Medium</option>
            <option value="HIGH">High</option>
            <option value="URGENT">Urgent</option>
          </select>
        </div>
        <button type="submit" disabled={creating} className="btn-primary">{creating ? 'Adding...' : 'Add task'}</button>
      </form>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {(['TODO', 'IN_PROGRESS', 'DONE'] as const).map((status) => (
          <div key={status} className="card p-4">
            <h3 className="font-semibold text-slate-700 mb-3">{status.replace('_', ' ')} ({grouped[status].length})</h3>
            <div className="space-y-2">
              {grouped[status].map((task) => (
                <div key={task.id} className="border border-slate-200 rounded-md p-3">
                  <div className="flex justify-between items-start gap-2">
                    <p className="text-sm font-medium">{task.title}</p>
                    <Badge label={task.priority} />
                  </div>
                  {task.description && <p className="text-xs text-slate-500 mt-1 line-clamp-2">{task.description}</p>}
                  <div className="flex justify-between items-center mt-2">
                    <span className="text-xs text-slate-400">
                      {task.assignee?.name || 'Unassigned'} {task.dueDate && `· ${formatDate(task.dueDate)}`}
                      {task.autoGenerated && ' · auto'}
                    </span>
                    <select
                      className="text-xs border border-slate-200 rounded px-1 py-0.5"
                      value={task.status}
                      onChange={(e) => updateStatus(task.id, e.target.value)}
                    >
                      <option value="TODO">To do</option>
                      <option value="IN_PROGRESS">In progress</option>
                      <option value="DONE">Done</option>
                      <option value="CANCELLED">Cancelled</option>
                    </select>
                  </div>
                </div>
              ))}
              {grouped[status].length === 0 && <p className="text-xs text-slate-400">No tasks.</p>}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
